# -*- coding: utf-8 -*-
"""OBJ-6b — EMIT THE ENUMERATION LANGSTON ASKED FOR INSTEAD OF THE PERCENTAGES.

His words: "not the percentages — the ENUMERATION. One committed row per instance: commit sha,
bucket, one-line basis. I re-derive the bucket from the commit myself and the percentage falls
out of a denominator I can reach. Rows with no commit are marked `transcript-only` and EXCLUDED
from any load-bearing figure."

⇒ this writes a table where EVERY ROW CITES A COMMIT HE CAN OPEN. The bucket is my reading; the
basis names the token that produced it, so he can disagree per row rather than per percentage.
Nothing here is a rate, deliberately.
"""
import subprocess, re, io, os, collections

os.chdir(r'C:\DawnTraderV3-old')
OUT = 'Claude Comms and Packages/Scope Files/B_MEASURE_GATE_LEG2_OBJ6B_ENUMERATION.md'
REF = subprocess.run(['git', 'rev-parse', 'origin/migration/aws-supabase'],
                     capture_output=True, text=True).stdout.strip()

SEP = '\x1e'
raw = subprocess.run(['git', 'log', REF, '--no-merges', '--format=%H%x1f%ad%x1f%s%x1f%b' + SEP,
                      '--date=short'], capture_output=True, text=True,
                     encoding='utf-8', errors='replace').stdout

TR = re.compile(r'^MISTAKE:\s*([a-z0-9][a-z0-9-]*)', re.M)

BASH = [
    (r'\bgit (log|show|grep|rev-list|diff|ls-tree|cat-file|status|stash|rev-parse|checkout)\b', 'git'),
    (r'\bgrep\b|\brg\b|\bripgrep\b', 'grep'),
    (r'\bmd5sum\b|\bwc -c\b|\bwc -l\b|\bstat\b', 'file-stat'),
    (r'\bpsql\b|\bSELECT\b|\bsupabase\b', 'db'),
    (r'\bcurl\b|\bHTTP \d{3}\b|\b404\b', 'http'),
    (r'\bssh\b|\bpm2\b|\btail\b|\bjournalctl\b', 'remote/log'),
    (r'\bpython3?\b|\bnode\b|\bnpm\b|\btsc\b', 'script'),
]
NONBASH = [
    (r'\bRead tool\b', 'Read tool'),
    (r'\bGrep tool\b|\bGlob tool\b', 'Grep/Glob tool'),
    (r'\bWebFetch\b|\bWebSearch\b', 'web tool'),
    (r'\bfrom memory\b|\bwithout (opening|reading|checking)\b|\brecall(ed|ing)?\b|\basserted? without\b',
     'NO INSTRUMENT (recalled/asserted)'),
    (r'\bthe (docs?|documentation) (say|said|states?)\b|\breported by\b|\btook .{0,12}on report\b',
     'reported fact / doc'),
]

rows = []
for chunk in raw.split(SEP):
    chunk = chunk.strip('\n')
    if not chunk:
        continue
    p = chunk.split('\x1f')
    if len(p) < 4:
        continue
    sha, date, subj, body = p
    for m in TR.finditer(body):
        if m.group(1) != 'wrong-object':
            continue
        b = [lab for pat, lab in BASH if re.search(pat, body, re.I)]
        n = [lab for pat, lab in NONBASH if re.search(pat, body, re.I)]
        if b and not n:
            bucket, basis = 'BASH', '+'.join(b)
        elif n and not b:
            bucket, basis = 'NON-BASH', '+'.join(n)
        elif b and n:
            bucket, basis = 'AMBIGUOUS', '+'.join(b) + ' | ' + '+'.join(n)
        else:
            bucket, basis = 'UNATTRIBUTED', 'no instrument token in the commit body'
        rows.append((sha, date, subj, bucket, basis))

counts = collections.Counter(r[3] for r in rows)
shas = len({r[0] for r in rows})

L = []
L.append('# OBJ-6b — THE ENUMERATION, ONE ROW PER INSTANCE')
L.append('')
L.append('**Owner:** CC-A · generated by `scripts/measure-gate/obj6b_enumerate.py` · ref `%s`' % REF)
L.append('')
L.append('⛔⛔ **THIS FILE EXISTS BECAUSE LANGSTON REFUSED THE PERCENTAGES AND ASKED FOR THE ROWS.** '
         'His words: *"I re-derive the bucket from the commit myself and the percentage falls out of a '
         'denominator I can reach."* ⇒ **every row below cites a commit he can open. The BUCKET is my '
         'reading; the BASIS names the token that produced it, so he can disagree PER ROW rather than '
         'per percentage.**')
L.append('')
L.append('✅ **PROVENANCE: every row is a `MISTAKE: wrong-object` trailer in a commit body reachable from '
         'the ref. NOTHING here is `transcript-only`, so nothing is excluded on that ground.** '
         '⚠️ **What IS transcript-only is the OTHER instrument — the tool-distribution measurement — '
         'which reads session JSONL on one laptop that Helsinki cannot reach. That leg stays '
         '`RULED ON REPORTED FACT` and is NOT load-bearing for the gate.**')
L.append('')
L.append('| bucket | instances |')
L.append('|---|---|')
for k in ('BASH', 'NON-BASH', 'AMBIGUOUS', 'UNATTRIBUTED'):
    L.append('| `%s` | %d |' % (k, counts.get(k, 0)))
L.append('| **total** | **%d instances on %d distinct commits** |' % (len(rows), shas))
L.append('')
L.append('⚠️ **INSTANCES ≠ COMMITS — some commits carry two trailers, and an earlier document '
         'called this figure a commit count. Both numbers are stated.**')
L.append('')
L.append('---')
L.append('')
L.append('| # | commit | date | bucket | basis | subject |')
L.append('|---|---|---|---|---|---|')
for i, (sha, date, subj, bucket, basis) in enumerate(rows, 1):
    s = subj.replace('|', '\\|')[:96]
    L.append('| %d | `%s` | %s | **%s** | %s | %s |' % (i, sha[:9], date, bucket, basis, s))
L.append('')

io.open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(L))
print('wrote %s' % OUT)
print('  %d instances on %d commits' % (len(rows), shas))
print('  ' + ' · '.join('%s=%d' % (k, v) for k, v in counts.most_common()))
