import fs from "fs/promises";
import path from "path";
import { db } from "../db";
import { lottieOversightLog, strategyMixLog } from "../../shared/schema";
import { desc } from "drizzle-orm";

export async function generatePhase30Report(): Promise<string> {
  try {
    console.log("[30.FX.Report] Generating Phase 30.FX.4-6 audit report...");
    
    const oversight = await db
      .select()
      .from(lottieOversightLog)
      .orderBy(desc(lottieOversightLog.createdAt))
      .limit(20);

    const mix = await db
      .select()
      .from(strategyMixLog)
      .orderBy(desc(strategyMixLog.createdAt))
      .limit(20);

    const report = `# Phase 30.FX.4–6 Report
Generated: ${new Date().toISOString()}

## Overview
This report summarizes the Lottie Oversight and Cross-Strategy Optimization activities.

## Lottie Oversight Log (Last 20 Events)
${oversight.length === 0 ? "No oversight events recorded yet." : ""}
${oversight.map(o => `- ${o.createdAt?.toISOString()}: **${o.event}** - Strategy: ${o.strategy || 'N/A'} - Status: ${o.status} (${o.reason || 'no reason'})`).join("\n")}

## Strategy Mix Changes (Last 20)
${mix.length === 0 ? "No strategy mix changes recorded yet." : ""}
${mix.map(m => `- ${m.createdAt?.toISOString()}: **${m.strategy}** → weight: ${m.newWeight} (from ${m.oldWeight || 'N/A'}) - Reason: ${m.reason || 'no reason'}`).join("\n")}

## Summary Statistics

### Lottie Oversight
- Total events: ${oversight.length}
- Active strategies: ${new Set(oversight.map(o => o.strategy).filter(Boolean)).size}
- Status breakdown:
${getStatusBreakdown(oversight)}

### Strategy Mix
- Total changes: ${mix.length}
- Affected strategies: ${new Set(mix.map(m => m.strategy)).size}
- Average new weight: ${mix.length > 0 ? (mix.reduce((sum, m) => sum + (m.newWeight || 0), 0) / mix.length).toFixed(2) : 'N/A'}

---
*Auto-generated by Phase 30.FX.A Audit System*
`;

    // Ensure audit directory exists
    const auditDir = path.join(process.cwd(), "audit");
    await fs.mkdir(auditDir, { recursive: true });
    
    // Write report to file
    const reportPath = path.join(auditDir, "phase30-fx4-6-report.md");
    await fs.writeFile(reportPath, report, "utf-8");
    
    console.log(`[30.FX.Report] ✅ Report generated: ${reportPath}`);
    return reportPath;
  } catch (error: any) {
    console.error("[30.FX.Report] Error generating report:", error.message);
    throw error;
  }
}

function getStatusBreakdown(oversight: any[]): string {
  const statusCounts = oversight.reduce((acc, o) => {
    const status = o.status || 'unknown';
    acc[status] = (acc[status] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);
  
  return Object.entries(statusCounts)
    .map(([status, count]) => `  - ${status}: ${count}`)
    .join("\n") || "  - No data";
}

// Auto-trigger on module import
if (require.main === module) {
  generatePhase30Report()
    .then(path => console.log(`Report saved to: ${path}`))
    .catch(err => console.error("Failed to generate report:", err));
}
