/**
 * B79.0n.UNIVERSE-DISCOVERY — seed extraction script.
 *
 * Reads the current XSTOCK_SPOT_REGISTRY Map literal from shared/asset-classes.ts
 * and emits two SQL artifacts to stdout:
 *   1. INSERT statements for xstock_spot_universe (the runtime universe snapshot)
 *   2. INSERT statements for xstock_spot_universe_overrides (manual curation flags
 *      — cryptoAdjacent / adr / sector-override carried forward from current
 *      hand-maintained registry; preserves institutional knowledge across the
 *      hardcoded-Map → DB-table transition).
 *
 * Output is committed alongside the 2026-05-21-b79-0n-universe-discovery.sql
 * migration so the seed is reviewable + regeneratable (Langston Q6 ACK).
 *
 * Usage:
 *   npx tsx scripts/b79-0n-universe-seed-extract.ts > /tmp/b79-0n-seed.sql
 *
 * Output shape:
 *   -- xstock_spot_universe seed (260 rows)
 *   INSERT INTO xstock_spot_universe (symbol, name, sector, crypto_adjacent, adr, source_chain) VALUES
 *     ('AAPL/USD', 'Apple', 'XLK', false, false, '{"seed": true, ...}'),
 *     ...
 *   ON CONFLICT (symbol) DO NOTHING;
 *
 *   -- xstock_spot_universe_overrides seed (~75 rows: cryptoAdjacent + adr + non-GICS sector classifications)
 *   INSERT INTO xstock_spot_universe_overrides (...) VALUES
 *     ('MSTR/USD', NULL, true, NULL, NULL, 'B79.0n.UNIVERSE-DISCOVERY seed: cryptoAdjacent treasury'),
 *     ...
 *   ON CONFLICT (symbol) DO NOTHING;
 */

import { XSTOCK_SPOT_REGISTRY, type XstockSpotEntry, type XstockSector } from '../shared/asset-classes';

const SEED_SOURCE_CHAIN_JSONB = JSON.stringify({
  coingecko: false,
  kraken_ws_accept: false,
  finnhub: false,
  override_applied: true,
  seed: true,
});

function sqlEscape(s: string): string {
  return s.replace(/'/g, "''");
}

function emitUniverseSeed(): void {
  const entries = Array.from(XSTOCK_SPOT_REGISTRY.entries());
  console.log(`-- xstock_spot_universe seed (${entries.length} rows extracted from shared/asset-classes.ts XSTOCK_SPOT_REGISTRY)`);
  console.log(`-- Generated by scripts/b79-0n-universe-seed-extract.ts`);
  console.log(`-- ON CONFLICT (symbol) DO NOTHING — idempotent partial-state replay safe (Langston Q6)`);
  console.log(``);
  console.log(`INSERT INTO xstock_spot_universe (symbol, name, sector, crypto_adjacent, adr, source_chain) VALUES`);
  const rows = entries.map(([symbol, entry]) => {
    const ca = entry.cryptoAdjacent === true ? 'true' : 'false';
    const adr = entry.adr === true ? 'true' : 'false';
    return `  ('${sqlEscape(symbol)}', '${sqlEscape(entry.name)}', '${entry.sector}', ${ca}, ${adr}, '${SEED_SOURCE_CHAIN_JSONB}'::jsonb)`;
  });
  console.log(rows.join(',\n'));
  console.log(`ON CONFLICT (symbol) DO NOTHING;`);
}

function emitOverrideSeed(): void {
  const entries = Array.from(XSTOCK_SPOT_REGISTRY.entries());
  // Override rows for symbols where the curated registry has cryptoAdjacent: true,
  // adr: true, OR a sector that diverges from what Finnhub's GICS classification
  // would return (INDEX_PROXY / BROAD_ETF / INTL_ETF — Finnhub returns generic
  // industry strings for ETFs that don't map cleanly to our internal taxonomy).
  const overrides = entries.filter(([_, entry]) => {
    return entry.cryptoAdjacent === true ||
           entry.adr === true ||
           entry.sector === 'INDEX_PROXY' ||
           entry.sector === 'BROAD_ETF' ||
           entry.sector === 'INTL_ETF';
  });

  console.log(``);
  console.log(`-- xstock_spot_universe_overrides seed (${overrides.length} rows: cryptoAdjacent / adr / non-GICS sector classifications)`);
  console.log(`-- Curated flags that cannot be auto-derived from Finnhub /stock/profile2 metadata.`);
  console.log(`-- Preserves institutional knowledge from hand-maintained XSTOCK_SPOT_REGISTRY.`);
  console.log(``);
  console.log(`INSERT INTO xstock_spot_universe_overrides (symbol, sector_override, crypto_adjacent_override, adr_override, name_override, notes) VALUES`);
  const rows = overrides.map(([symbol, entry]) => {
    // sector_override: only set if sector is non-GICS (INDEX_PROXY / BROAD_ETF /
    // INTL_ETF); otherwise NULL so Finnhub-derived value wins on refresh.
    const sectorOverride = (entry.sector === 'INDEX_PROXY' || entry.sector === 'BROAD_ETF' || entry.sector === 'INTL_ETF')
      ? `'${entry.sector}'`
      : 'NULL';
    const cryptoAdjOverride = entry.cryptoAdjacent === true ? 'true' : 'NULL';
    const adrOverride = entry.adr === true ? 'true' : 'NULL';
    const notes = [
      entry.cryptoAdjacent === true ? 'cryptoAdjacent' : null,
      entry.adr === true ? 'ADR' : null,
      (entry.sector === 'INDEX_PROXY' || entry.sector === 'BROAD_ETF' || entry.sector === 'INTL_ETF') ? `sector=${entry.sector}` : null,
    ].filter(x => x !== null).join('; ');
    return `  ('${sqlEscape(symbol)}', ${sectorOverride}, ${cryptoAdjOverride}, ${adrOverride}, NULL, 'B79.0n.UNIVERSE-DISCOVERY seed: ${sqlEscape(notes)}')`;
  });
  console.log(rows.join(',\n'));
  console.log(`ON CONFLICT (symbol) DO NOTHING;`);
}

emitUniverseSeed();
emitOverrideSeed();
