export const STRATEGY_PRESETS = {
  VWAP_PULLBACK: {
    Conservative: {
      maxConcurrentPositions: 3,
      riskPerTrade: 0.005,
      takeProfitR: 1.5,
      stopLossR: 1,
      cooldownMinutes: 10,
      vwapLookbackMin: 30,
      pullbackPct: 0.008,
      minVolumeUsd: 25000,
    },
    Balanced: {
      maxConcurrentPositions: 5,
      riskPerTrade: 0.01,
      takeProfitR: 2,
      stopLossR: 1,
      cooldownMinutes: 5,
      vwapLookbackMin: 20,
      pullbackPct: 0.01,
      minVolumeUsd: 10000,
    },
    Aggressive: {
      maxConcurrentPositions: 10,
      riskPerTrade: 0.02,
      takeProfitR: 3,
      stopLossR: 1,
      cooldownMinutes: 2,
      vwapLookbackMin: 10,
      pullbackPct: 0.015,
      minVolumeUsd: 5000,
    },
  },
  ABCD_LONG: {
    Conservative: {
      maxConcurrentPositions: 2,
      riskPerTrade: 0.005,
      takeProfitR: 1.5,
      stopLossR: 1,
      cooldownMinutes: 15,
      minAtoBStrength: 1.5,
      cPullbackPctMax: 0.12,
      dBreakoutBufferPct: 0.003,
    },
    Balanced: {
      maxConcurrentPositions: 4,
      riskPerTrade: 0.01,
      takeProfitR: 2,
      stopLossR: 1,
      cooldownMinutes: 8,
      minAtoBStrength: 1.2,
      cPullbackPctMax: 0.15,
      dBreakoutBufferPct: 0.005,
    },
    Aggressive: {
      maxConcurrentPositions: 8,
      riskPerTrade: 0.02,
      takeProfitR: 2.5,
      stopLossR: 1,
      cooldownMinutes: 3,
      minAtoBStrength: 1.1,
      cPullbackPctMax: 0.18,
      dBreakoutBufferPct: 0.007,
    },
  },
  SMA_TREND_RIDE: {
    Conservative: {
      maxConcurrentPositions: 3,
      riskPerTrade: 0.005,
      takeProfitR: 1.5,
      stopLossR: 1,
      cooldownMinutes: 15,
      fastSma: 10,
      slowSma: 60,
      trendStrengthMin: 0.5,
    },
    Balanced: {
      maxConcurrentPositions: 5,
      riskPerTrade: 0.01,
      takeProfitR: 2,
      stopLossR: 1,
      cooldownMinutes: 5,
      fastSma: 10,
      slowSma: 50,
      trendStrengthMin: 0.4,
    },
    Aggressive: {
      maxConcurrentPositions: 10,
      riskPerTrade: 0.02,
      takeProfitR: 3,
      stopLossR: 1,
      cooldownMinutes: 2,
      fastSma: 5,
      slowSma: 30,
      trendStrengthMin: 0.3,
    },
  },
  BREAKOUT: {
    Conservative: {
      maxConcurrentPositions: 2,
      riskPerTrade: 0.005,
      takeProfitR: 1.5,
      stopLossR: 1,
      cooldownMinutes: 15,
      minConsolidationBars: 12,
      maxRangeWidth: 0.03,
      breakoutBuffer: 0.005,
      volumeMultiplier: 1.5,
      trailingStopEnabled: true,
      maxHoldingHours: 8,
    },
    Balanced: {
      maxConcurrentPositions: 4,
      riskPerTrade: 0.01,
      takeProfitR: 2,
      stopLossR: 1,
      cooldownMinutes: 8,
      minConsolidationBars: 8,
      maxRangeWidth: 0.04,
      breakoutBuffer: 0.008,
      volumeMultiplier: 2,
      trailingStopEnabled: true,
      maxHoldingHours: 6,
    },
    Aggressive: {
      maxConcurrentPositions: 8,
      riskPerTrade: 0.02,
      takeProfitR: 2.5,
      stopLossR: 1,
      cooldownMinutes: 3,
      minConsolidationBars: 5,
      maxRangeWidth: 0.05,
      breakoutBuffer: 0.01,
      volumeMultiplier: 2.5,
      trailingStopEnabled: true,
      maxHoldingHours: 4,
    },
  },
  MEAN_REVERSION: {
    Conservative: {
      maxConcurrentPositions: 3,
      riskPerTrade: 0.005,
      takeProfitR: 1.2,
      stopLossR: 1,
      cooldownMinutes: 10,
      meanType: 'sma',
      smaLength: 50,
      deviationThreshold: 0.03,
      minRangeTouches: 4,
      partialExitPercent: 50,
      stopLossBuffer: 0.01,
    },
    Balanced: {
      maxConcurrentPositions: 5,
      riskPerTrade: 0.01,
      takeProfitR: 1.5,
      stopLossR: 1,
      cooldownMinutes: 5,
      meanType: 'sma',
      smaLength: 30,
      deviationThreshold: 0.04,
      minRangeTouches: 3,
      partialExitPercent: 50,
      stopLossBuffer: 0.012,
    },
    Aggressive: {
      maxConcurrentPositions: 10,
      riskPerTrade: 0.02,
      takeProfitR: 2,
      stopLossR: 1,
      cooldownMinutes: 2,
      meanType: 'sma',
      smaLength: 20,
      deviationThreshold: 0.05,
      minRangeTouches: 2,
      partialExitPercent: 50,
      stopLossBuffer: 0.015,
    },
  },
  RANGE_TRADING: {
    Conservative: {
      maxConcurrentPositions: 3,
      riskPerTrade: 0.005,
      takeProfitR: 1.5,
      stopLossR: 1,
      cooldownMinutes: 15,
      minRangeDurationHours: 24,
      minRangeWidth: 0.04,
      minBoundaryTouches: 4,
      entryZoneWidth: 0.003,
      stopLossBeyond: 0.01,
    },
    Balanced: {
      maxConcurrentPositions: 5,
      riskPerTrade: 0.01,
      takeProfitR: 2,
      stopLossR: 1,
      cooldownMinutes: 8,
      minRangeDurationHours: 12,
      minRangeWidth: 0.03,
      minBoundaryTouches: 3,
      entryZoneWidth: 0.005,
      stopLossBeyond: 0.012,
    },
    Aggressive: {
      maxConcurrentPositions: 8,
      riskPerTrade: 0.02,
      takeProfitR: 2.5,
      stopLossR: 1,
      cooldownMinutes: 3,
      minRangeDurationHours: 6,
      minRangeWidth: 0.02,
      minBoundaryTouches: 2,
      entryZoneWidth: 0.007,
      stopLossBeyond: 0.015,
    },
  },
  VWAP_BOUNCE: {
    Conservative: {
      maxConcurrentPositions: 3,
      riskPerTrade: 0.005,
      takeProfitR: 1.5,
      stopLossR: 1,
      cooldownMinutes: 10,
      vwapProximity: 0.003,
      minVWAPSlope: 0.002,
      trailingToVWAP: true,
      maxPullbackBars: 5,
      partialExitR: 1.5,
    },
    Balanced: {
      maxConcurrentPositions: 5,
      riskPerTrade: 0.01,
      takeProfitR: 2,
      stopLossR: 1,
      cooldownMinutes: 5,
      vwapProximity: 0.005,
      minVWAPSlope: 0.003,
      trailingToVWAP: true,
      maxPullbackBars: 7,
      partialExitR: 2,
    },
    Aggressive: {
      maxConcurrentPositions: 10,
      riskPerTrade: 0.02,
      takeProfitR: 2.5,
      stopLossR: 1,
      cooldownMinutes: 2,
      vwapProximity: 0.008,
      minVWAPSlope: 0.005,
      trailingToVWAP: true,
      maxPullbackBars: 10,
      partialExitR: 2.5,
    },
  },
  LIQUIDITY_TRAP: {
    Conservative: {
      maxConcurrentPositions: 2,
      riskPerTrade: 0.005,
      takeProfitR: 1.5,
      stopLossR: 1,
      cooldownMinutes: 20,
      maxTrapExtension: 0.008,
      trapReturnBars: 2,
      minStopZoneSize: 'medium',
      minLevelTouches: 4,
      volumeRatio: 1.5,
    },
    Balanced: {
      maxConcurrentPositions: 4,
      riskPerTrade: 0.01,
      takeProfitR: 2,
      stopLossR: 1,
      cooldownMinutes: 10,
      maxTrapExtension: 0.012,
      trapReturnBars: 2,
      minStopZoneSize: 'medium',
      minLevelTouches: 3,
      volumeRatio: 1.8,
    },
    Aggressive: {
      maxConcurrentPositions: 6,
      riskPerTrade: 0.02,
      takeProfitR: 2.5,
      stopLossR: 1,
      cooldownMinutes: 5,
      maxTrapExtension: 0.015,
      trapReturnBars: 3,
      minStopZoneSize: 'small',
      minLevelTouches: 2,
      volumeRatio: 2,
    },
  },
} as const;

export type StrategyPresetGroup = keyof typeof STRATEGY_PRESETS;
export type StrategyPresetName = keyof typeof STRATEGY_PRESETS[StrategyPresetGroup];
