"""Even split by CONNECTED GROUPS (Kyle 2026-09-28): items that depend on each other stay with one session;
previous ownership is not a factor. Kyle owns no rows: his decisions/actions sit inside the owning session's row."""
CLUSTERS = [
 ("CC-C", "Prices and the exit price path; paper sizing (in flight); the paper standard and judging the evidence", [
   "B-OHLC-FRAME-GUARD", "B-REST-SIDES-TO-CACHE", "B-BOOK-STATE-RESTART-DURABLE", "F-G-1-REOPEN", "B-PRICE-SIDE-BY-JOB",
   "B-XSTOCK-LIVE-FEED", "row:6", "B-PRICE-STALENESS-BOUND", "B-EQUITY-RECONNECT-STALL-TIMER", "#506", "B-BOOK-SUBSCRIPTION-REACH",
   "B-CRYPTO-MARK-AGE-GATE", "B-XSTOCK-SESSION-FRESHNESS", "B-XSTOCK-ENTRY-COMPARATOR", "B-DECIDED-INTENT-INDEX", "B-POST-GRID-MUTATION-CENSUS",
   "row:7", "CODEX-PRICING-REVIEW", "B-EXIT-TRIGGER-FILL-PARITY", "B-EXIT-TICKER-LEG-ADAPTER-SIDES", "B-XSTOCK-BID-TRIGGER-RELAND",
   "B-BOOK-STATE-RING-INDEPENDENT-BOUND", "#204", "row:3h.b", "EXIT-PATH-AUDIT-MAP", "B-GRID-LIVE-PATH-PARITY", "B-INTENT-ENTRY-PARITY",
   "RESTING-ORDER-DEADLINE", "#630", "row:8", "B-DECISION-INSTANT-QUOTE", "B-EXIT-DECISION-RUNG-STAMP", "B-VTS-MARK-SIDE",
   "B-VTS-NO-DECISION-VALVE", "#1072", "B-GRID-REFUSAL-RATE", "B-IMPLEMENTATION-SHORTFALL", "B-TARGET-FABRICATION", "#1033",
   "LIVE-FEE-SCHEDULE", "B-KRAKEN-FEE-WATCH", "#296", "B-EXIT-LATCH-INVESTIGATION",
   "B-SIZING-DEC-RESTORE", "#628", "#692", "#977", "#513",
   "PAPER-STANDARD", "rm:21-3b", "rm:19-11"]),
 ("Infra", "Identity, the coin list and exclusions; restarts, deploys, security and the servers; what the diagnostic screens show", [
   "B-UNIVERSE-REFRESH-ACTS", "B-SYMBOL-CLASS-IDENTITY", "B-RTB-SIGNAL-IDENTITY", "B-VTS-CLASS-LABEL-INTEGRITY", "B-CLOSED-TRADES-CLASS-BACKFILL",
   "NONFIAT-FORK", "B-NONFIAT-QUOTE-DENOMINATION", "B-QUOTE-ADMISSION-LEGACY-SWEEP", "B-QUOTE-LEG-INTEGRITY", "B-PRICE-FLOOR-REVIEW",
   "B-VENUE-PAIRS-REINIT", "B-SCAN-BREADTH-DECLINE", "B-WS-SUBSCRIBE-CLASS-FILTER",
   "B-SCHEDULER-FIRST-TICK", "#585", "B-TEC-PRIME-BOOT-RACE", "#521", "B-ENGINE-STOP-DURATION-COLUMN", "#619", "#166",
   "#681", "#168", "P19-B12", "DISK-HEADROOM", "RULINGS-DURABILITY", "B-SEC-HARDEN", "B-SSH-KEY-CENSUS", "#615", "COLTRANE-PARITY",
   "B-DASHBOARD-AUTH-RACE", "KRAKEN-LIVE-KEY", "B-STRING-TRUTHINESS-GUARDS", "B-GUARD-COVERAGE-AUDIT", "DEAD-CODE-REACHABILITY",
   "B-LEARNING-SYSTEM-CENSUS", "B-MODE-PREDICATE-SWEEP", "PLAN-ID-COLLISIONS",
   "B-WS-V1-RESIDUE-SWEEP", "rm:16.6", "B-VENUE-QUIET-ALERTING", "STAGING-RESIZE", "CONTEXT-BRIDGE-TTL", "#150",
   "B-VALIDATE-OBSERVABILITY", "B-DIAG-READ-INTEGRITY", "B-FILTER-DIAG-XSTOCK", "#664", "#419", "#549", "#561", "#547"]),
 ("CC-B", "Signals, strategies, the SQE and RTB; learning data; trade-distance and strategy tuning", [
   "#233", "#199", "row:3m-ENUM", "B-SILENT-STRATEGY-CENSUS", "#574", "B-RTB-REFRESH-CONSOLIDATE", "#570", "#699", "rm:19.2",
   "B-ENTRY-LEVEL-RECHECK", "#972", "#566",
   "B-OUTCOME-CORPUS-CAPTURE", "B-PAPER-LANE-PROVENANCE", "T-W20C-SCALAR-LEG", "#515", "#631", "#504", "B-TRADE-RECORD-JOINABILITY",
   "B-VPNL-WRITER-BOUND", "#658", "#220", "B-ARCHIVE-WRITER-LIFECYCLE", "#1078", "B-EPOCH-PARITY-FENCE", "B-ROLLBACK-EPOCH-FORWARD", "#590",
   "B-PROVENANCE-LOSS-CENSUS", "#231", "row:9",
   "B-EXCURSION-RECORD", "rm:25-17", "rm:25-17b", "rm:25-20", "B-TARGET-MULTIPLE-VS-HORIZON", "rm:25-26", "B-EXIT-MAKER-VS-TAKER-REVIEW",
   "#648", "#201", "#529", "B-FAMILY-POOL-REACHABILITY", "B-IDEAL-POOL-STARVATION", "#149", "#221", "B-SQE-DEADCODE-PURGE", "ACCUMULATION-GATE"]),
 ("CC-A", "Trade records and costs; scores, regimes and gates; the xStock tuning studies; risk controls; the live engine; the final end-to-end audit", [
   "B-CLOSE-WRITER-COSTS", "B-COST-MATH-CONSOLIDATION", "#527", "#914", "rm:25-18", "#645", "rm:16.7", "#588", "rm:25-4", "rm:25-2", "rm:25-10", "rm:25-7", "rm:25-3", "rm:25-15", "rm:25-19", "#644",
   "#634", "#632", "B-KILLSWITCH-DENOMINATOR", "B-TOTAL-DRAWDOWN-WARNING", "#519", "rm:25-12", "rm:25-13", "rm:25-14", "rm:25-9",
   "rm:21.1.a", "rm:21-3c", "rm:21-3d", "rm:19-10", "rm:21.1", "#322", "P19-B6.10", "rm:21-3a", "#517", "rm:21.3", "rm:19-9", "25-11a",
   "PROCESS-DEATH-FORM", "B-VENUE-RESTING-EXITS", "rm:25-16", "DAY-ONE-NUMBERS", "rm:21.2", "rm:19-17b",
   "#522", "#235", "B-TRADING-ENGINE-REMOVAL", "#589", "B-LIVE-PROCESS-SPLIT", "B-PLAN-CURRENCY-CHECK", "#218"]),
]
