"""The working ORDER of the sprint to live (CC-B draft, 2026-09-28, for Langston's review then Kyle).
Two tracks run side by side and meet at go-live:
  Track A — the trading system: foundations -> mechanics (+ learning data alongside) -> tuning -> the evidence.
  Track B — live-mode readiness: the environment decision, safety now, risk controls, restart/ops, the live engine, go-live prep.
Wave 0 is this week's urgent and cheap items. Within a wave, the listed order is the working order; an item marked
'after X' must wait for X. Every sprint item must appear exactly once (asserted)."""
import io, json, os
HERE = os.path.dirname(os.path.abspath(__file__))

WAVES = [
 ("0", "NOW — urgent, cheap, or already in flight. GATE: staging is held at bc199185e for the 8a-P4c window (to 2026-09-30 00:00Z); the held deploy is not before 2026-10-02 20:10Z (GOVERNANCE_EXCEPTIONS.md:28) - the deploy-drift alerts clear on that deploy", [
   ("B-PLAN-CURRENCY-CHECK", "keeps this plan current: checker close-diff rule + weekly census alert, then the CLAUDE.md pointer swap (Langston ruling, OLD Claude)"),
   ("B-XSTOCK-BID-TRIGGER-RELAND", "midpoint off (Kyle 2026-09-28: finished and deployed BEFORE the sprint starts): paper xStock stop/target triggers back on the bid"),
   ("B-VTS-MARK-SIDE", "midpoint off, before the sprint: the VTS xStock prices on the right side (8a-P4c increments 2-3)"),
   ("B-VTS-NO-DECISION-VALVE", "midpoint off, before the sprint: a VTS trade with no usable sell price no longer books its timeout at the midpoint"),
   ("RULINGS-DURABILITY", "cheap and irreversible if lost: copy Langston's rulings file to a read-only replica"),
   ("DISK-HEADROOM", "database at 81% (critical): confirm the October 1 move of August to warm storage lands; then (Kyle 2026-09-28) move one month of one-minute price bars as the proof and flip their hot window 365 -> 30 days (~19 GB out); then measure months of headroom"),
   ("CONTEXT-BRIDGE-TTL", "this week: make the retention demonstrably free bytes on a named table - install the missing 14-day job (1.48 GB); #688 (four monthly-partitioned tables) rides the disk item"),
   ("PAPER-STANDARD", "set the numbers for 'comfortable in paper' BEFORE the evidence comes in"),
   ("B-SIZING-DEC-RESTORE", "wave 0 - KYLE 2026-09-29 (supersedes option c): one shared pot; paper reset to a $3,000 balance - only the paper dashboard starts from zero, nothing deleted, open positions closed and labelled as closed by the reset; sized by the max-position % guardrail, MONITORED and ADJUSTED so each trade stays near $140-150 (5% to start), about 20 open at 100% exposure; RETIRE the open-slots guardrail (rule 18); the obj-1 size formula correction (#698 am.1) comes first"),
   ("#628", "with B-SIZING-DEC-RESTORE: its two sizing sites"),
   ("#521", "wave 0 (Langston F11): nothing notices a dead engine - a silent halt voids every observation window"),
   ("PLAN-ID-COLLISIONS", "a chore, not mechanics (Langston): no two plan items share a number"),
   ("B-OHLC-FRAME-GUARD", "in flight: only the on-screen check is left"),
   ("B-REST-SIDES-TO-CACHE", "built and reviewed: ships in the ONE held deploy, not before 2026-10-02 20:10Z"),
   ("B-BOOK-STATE-RESTART-DURABLE", "built and reviewed: same held deploy"),
   ("F-G-1-REOPEN", "the OHLC writer can put an older bar over a newer one — it feeds the bars signals are built from"),
   ("B-PRICE-SIDE-BY-JOB", "in flight: its xStock increments follow the 09-30 window"),
 ]),
 ("A1", "TRACK A · Foundations — the things that corrupt everything downstream", [
   ("B-UNIVERSE-REFRESH-ACTS", "first link of the identity chain"),
   ("B-SYMBOL-CLASS-IDENTITY", "after B-UNIVERSE-REFRESH-ACTS: a ticker shared by a coin and a stock becomes two instruments"),
   ("B-RTB-SIGNAL-IDENTITY", "after B-SYMBOL-CLASS-IDENTITY"),
   ("B-VTS-CLASS-LABEL-INTEGRITY", "after B-SYMBOL-CLASS-IDENTITY: correct the mislabelled VTS rows"),
   ("B-CLOSED-TRADES-CLASS-BACKFILL", "after B-SYMBOL-CLASS-IDENTITY"),
   ("#150", "after B-SYMBOL-CLASS-IDENTITY: the RTB asset-class column made NOT NULL after a zero-null soak"),
   ("NONFIAT-FORK", "Kyle's decision: exclude plain currency pairs and non-dollar crypto now"),
   ("B-NONFIAT-QUOTE-DENOMINATION", "the exclusion itself, if small"),
   ("B-QUOTE-ADMISSION-LEGACY-SWEEP", "with the exclusion: what the old allowed-pairs list is for"),
   ("B-QUOTE-LEG-INTEGRITY", "with the exclusion"),
   ("B-PRICE-FLOOR-REVIEW", "replace the $0.25 floor with a real market-depth test"),
   ("B-VENUE-PAIRS-REINIT", "a changed exchange price step must not refuse orders"),
   ("B-SCAN-BREADTH-DECLINE", "why the scanner sees so few pairs — breadth feeds selection"),
   ("B-XSTOCK-LIVE-FEED", "the xStock feed became our trading feed without a decision — decide and fix"),
   ("row:6", "a bound on how old a price may be when used"),
   ("B-PRICE-STALENESS-BOUND", "the last-known-good price is re-served with no age bound"),
   ("B-EQUITY-RECONNECT-STALL-TIMER", "a stalled xStock reconnect leaves positions unwatched"),
   ("B-WS-SUBSCRIBE-CLASS-FILTER", "the crypto subscribe set is not class-filtered"),
   ("#506", "book subscriptions never unsubscribe"),
   ("B-BOOK-SUBSCRIPTION-REACH", "after #506: subscribe the order book for the whole pool, not ~3 coins"),
   ("B-CRYPTO-MARK-AGE-GATE", "crypto mark age"),
   ("#977", "the shared price-cache refresh lane for open positions runs but nothing subscribes - staleness hits selection (CC-C)"),
   ("B-XSTOCK-SESSION-FRESHNESS", "xStock entry-age limit vs the exit standard Kyle ruled"),
   ("B-XSTOCK-ENTRY-COMPARATOR", "xStock entry-price cross-check"),
   ("B-DECIDED-INTENT-INDEX", "xStock's three definitions of 'the price' from one frame"),
   ("B-POST-GRID-MUTATION-CENSUS", "what changes a stop after it is rounded"),
   ("row:7", "the VTS reads prices through the shared accessor"),
   ("#1033", "an absent volume is stored as zero and the liquidity filter reads it"),
   ("#972", "xStock ATR reads empty around the open and close"),
   ("#566", "volatility measured with a lag"),
   ("CODEX-PRICING-REVIEW", "after the price items: an independent review of the whole price layer"),
 ]),
 ("A2", "TRACK A · Mechanics, stage by stage — can start as A1's pieces land", [
   ("#233", "signals: drift and volume inputs fed as fixed defaults"),
   ("#199", "strategies: xStock volume confirmation removed for lack of an honest feed"),
   ("row:3m-ENUM", "strategies: volatility_edge's pattern path is silently dead"),
   ("B-SILENT-STRATEGY-CENSUS", "strategies: three wired strategies never evaluated"),
   ("B-TARGET-FABRICATION", "signals: default targets the strategy never chose"),
   ("#574", "SQE: a made-up volatility input in the ranker"),
   ("B-RTB-REFRESH-CONSOLIDATE", "RTB: the net-EV backstop removed on thin evidence"),
   ("#570", "RTB: one refresh bucket fires but does not refresh"),
   ("#699", "RTB: does promotion evict, or is the screen stale"),
   ("rm:19.2", "SQE: verify every score calculates correctly"),
   ("B-ENTRY-LEVEL-RECHECK", "open: re-check a signal's levels against the current price before the fill"),
   ("B-INTENT-ENTRY-PARITY", "open: two entry routes bypass the price grid"),
   ("B-GRID-LIVE-PATH-PARITY", "open: grid rounding on the live order path"),
   ("RESTING-ORDER-DEADLINE", "open: a resting order's deadline runs even when no price is usable"),
   ("#630", "open: exercise the maker-order deadline once"),
   ("B-EXIT-TRIGGER-FILL-PARITY", "close: exits fire on the price they would fill at"),
   ("B-EXIT-TICKER-LEG-ADAPTER-SIDES", "close: the exit path sees both price sides"),
   ("B-BOOK-STATE-RING-INDEPENDENT-BOUND", "close: xStock exit plausibility bound"),
   ("#204", "close: xStock stop prices at the wrong scale"),
   ("row:3h.b", "close: remove the second exit implementation"),
   ("B-EXIT-LATCH-INVESTIGATION", "close: is the hold-past-target a label or a real exit defect"),
   ("EXIT-PATH-AUDIT-MAP", "close: map the exit audit's items to homes"),
   ("#166", "close: the TEC stale-cache fence keeps firing"),
   ("B-CLOSE-WRITER-COSTS", "close: no close without a trade record, no invented zero fees"),
   ("B-SCHEDULER-FIRST-TICK", "restarts: every scheduled job runs twice after a restart"),
   ("#585", "restarts: auto-resume skips a malformed session"),
   ("B-STRING-TRUTHINESS-GUARDS", "hygiene: guards that treat '0' as true"),
   ("B-GUARD-COVERAGE-AUDIT", "hygiene: which guards cover which paths"),
   ("B-LEARNING-SYSTEM-CENSUS", "hygiene: old learning systems still wired"),
   ("DEAD-CODE-REACHABILITY", "hygiene (Langston C6): rules on ALL 22 legacy items - the 5 removals below AND the 17 in the after-live 'Legacy and dead-code cleanup' group; any it finds reachable from a trade joins the sprint by the section-2 intake test, the rest stay after live"),
   ("B-TRADING-ENGINE-REMOVAL", "legacy removal, after the census confirms it dead: the older second trading engine (Kyle 2026-09-28)"),
   ("B-SQE-DEADCODE-PURGE", "legacy removal, after the census: a dead SQE copy that checks fewer gates"),
   ("rm:16.6", "legacy removal, after the census: the old trailing-percent exit code, so it cannot re-enter a live exit"),
   ("#589", "legacy removal, after the census: the unused calibrated-profit calculator"),
   ("B-WS-V1-RESIDUE-SWEEP", "legacy removal, after the census: the dead first-generation Kraken price handler"),
   ("#218", "legacy removal, after the census: a dead function carrying a hardcoded fee default"),
   ("B-MODE-PREDICATE-SWEEP", "hygiene: readers that would mix live and paper P&L"),
   ("row:8", "paper truth: fill-integrity detector"),
   ("B-COST-MATH-CONSOLIDATION", "paper truth: one home for cost maths"),
   ("#527", "paper truth: xStock friction components"),
   ("B-IMPLEMENTATION-SHORTFALL", "paper truth: separate stale-signal cost from execution cost"),
   ("B-GRID-REFUSAL-RATE", "paper truth: how often the grid refuses"),
   ("B-VALIDATE-OBSERVABILITY", "paper truth: make validation failures visible"),
   ("B-DIAG-READ-INTEGRITY", "paper truth: diagnostics that read a status code as data"),
   ("B-FILTER-DIAG-XSTOCK", "paper truth: the empty xStock decline table"),
   ("#664", "paper truth: a hardcoded 'strategies evaluated'"),
   ("#419", "paper truth: funnel counts under errors"),
   ("#549", "paper truth: Open Trades field gaps"),
   ("#561", "paper truth: volume / order book columns in Open Trades"),
   ("#547", "paper truth: the Analyst's July findings (owner reads)"),
   ("B-EPOCH-PARITY-FENCE", "moved ahead of row:9 (Langston 2026-09-28): one home for the calibration epoch AND stamp the resolved epoch onto each trade row at write time (closed_trades.calibration_state is a dead column today) - so a per-cell restart becomes a checkable row filter, dated by DEPLOY (epoch rule 7)"),
   ("row:9", "THE LEARNING-RECORD RESTART (Kyle 2026-09-28, Langston AGREE WITH CHANGES): moved from the end of A3 to after the LAST fix that changes what a closed trade looks like - the test, applied once per row by its owner: does it change entry_price, exit_price, quantity, the cost/fee terms or the class/strategy label on a closed trade? The prerequisites, by key (S2-enforced): after B-XSTOCK-BID-TRIGGER-RELAND, after B-VTS-MARK-SIDE, after B-VTS-NO-DECISION-VALVE, after B-SIZING-DEC-RESTORE, after #628, after B-REST-SIDES-TO-CACHE, after B-BOOK-STATE-RESTART-DURABLE, after F-G-1-REOPEN, after B-PRICE-SIDE-BY-JOB, after B-SYMBOL-CLASS-IDENTITY, after B-RTB-SIGNAL-IDENTITY, after B-XSTOCK-LIVE-FEED, after row:6, after B-PRICE-STALENESS-BOUND, after B-CRYPTO-MARK-AGE-GATE, after #977, after B-XSTOCK-SESSION-FRESHNESS, after B-XSTOCK-ENTRY-COMPARATOR, after B-DECIDED-INTENT-INDEX, after B-POST-GRID-MUTATION-CENSUS, after row:7, after #972, after #566, after B-TARGET-FABRICATION, after B-ENTRY-LEVEL-RECHECK, after B-INTENT-ENTRY-PARITY, after B-GRID-LIVE-PATH-PARITY, after RESTING-ORDER-DEADLINE, after B-EXIT-TRIGGER-FILL-PARITY, after B-EXIT-TICKER-LEG-ADAPTER-SIDES, after B-BOOK-STATE-RING-INDEPENDENT-BOUND, after #204, after row:3h.b, after #166, after B-CLOSE-WRITER-COSTS, after B-COST-MATH-CONSOLIDATION, after #527. Not prerequisites: B-VTS-CLASS-LABEL-INTEGRITY and B-CLOSED-TRADES-CLASS-BACKFILL (they repair history in place). It must STATE which populations it restarts (active paper, VTS, the rejected arm). after B-EPOCH-PARITY-FENCE. AFTER THE RESTART, three cases, named: (1) a fix that changes no trade outcome restarts nothing; (2) one that changes one strategy or one class restarts only that cell, dated by deploy, read through the stamped epoch; (3) one that changes outcomes across ALL cells is a global restart"),
   ("#522", "LAST in A2: the full runtime pipeline audit, both classes, end to end"),
   ("#235", "with #522: the crypto pipeline validated end to end"),
 ]),
 ("A3", "TRACK A · Learning data — alongside A2; must finish before tuning reads the data", [
   ("B-OUTCOME-CORPUS-CAPTURE", "what each VTS trade earned, recorded durably, with a measured/defaulted flag on its inputs. NOT a deletion clock: the 90-day delete was fixed 2026-07-30/08-06 (365 days, archive before delete); nothing is due for deletion before 2027-05"),
   ("B-EXCURSION-RECORD", "early (Langston F5): capture costs calendar time - record how far trades travel; rm:25-17b is blocked on it by ruling"),
   ("rm:25-9", "early (Langston F5): xStock per-pair correlation data accumulates from here"),
   ("B-PAPER-LANE-PROVENANCE", "paper records its decision inputs"),
   ("T-W20C-SCALAR-LEG", "after B-PAPER-LANE-PROVENANCE: capture integrity - the parity harness proves recorded history replays to the same decisions"),
   ("#515", "remaining learning columns on the active path"),
   ("#631", "entry-mode fields on the active archive"),
   ("#504", "regime on maker/taker shadow rows"),
   ("#513", "the VTS books maker target exits the way the paper lane would"),
   ("B-DECISION-INSTANT-QUOTE", "the exact quote at decision time"),
   ("B-EXIT-DECISION-RUNG-STAMP", "which price rung an exit used"),
   ("B-TRADE-RECORD-JOINABILITY", "trade records join across stores"),
   ("B-VPNL-WRITER-BOUND", "an unbounded learning column"),
   ("#658", "VTS posture multipliers contaminating learning rows"),
   ("#220", "an error thrown 64,494 times in VTS strategy runs"),
   ("#1072", "the price-history recorder's frozen symbol set"),
   ("B-ARCHIVE-WRITER-LIFECYCLE", "the archive writer's lifecycle"),
   ("#1078", "B-ARCHIVE-FLUSH-DRAIN-ORDER: the writer drains its buffer before it holds a slot, so a slot timeout throws the rows away (670 on 2026-09-28) - in the sprint because it loses learning data"),
   ("B-ROLLBACK-EPOCH-FORWARD", "epochs across a rollback"),
   ("#590", "calibration store reset at the formula change"),
   ("B-PROVENANCE-LOSS-CENSUS", "where decision provenance is lost"),
   ("#231", "ablation record id gap"),
 ]),
 ("A4", "TRACK A · Tuning — reads the clean data; costs -> geometry -> strategies -> regimes -> scores -> gates -> ranking", [
   ("ACCUMULATION-GATE", "FIRST in A4 (Langston F4, conditions 2-3, clock ruling 2026-09-28): closes per cell only when the floor is MET or the cell is PUBLISHED UNDERPOWERED - naming a floor never closes it. Counts from row:9. POPULATIONS, named per item: ACTIVE = closed_trades paper (12.1/day all-time, 8.3 last 30 days, 7.4 last 7 on 2026-09-28 - use the current rate); VTS = vts_open_trades closed (~1,060/day); REJECTED = the VTS-tagged refused signals simulated to close. THE DISTRIBUTION BINDS, NOT THE START DATE: at a floor of 30 on the active lane, 8 of 38 strategy x class cells get there inside 90 days and 30 do not at any start date (21 have never traded) - Step 1 must state what happens to a permanently underpowered cell; #644 (exploration subsidy) is one of the answers and its position is re-argued there. FIELDS: an item that needs a field captured in A3 counts only rows carrying it - it prints n_total and n_with_field and closes on n_with_field; rows missing the field are excluded, never defaulted (#546)"),
   ("#914", "costs: the per-leg cost term - after ACCUMULATION-GATE; cell = per class x fee side; population = ACTIVE + VTS; a cell below the floor is published UNDERPOWERED, never fitted"),
   ("rm:25-18", "costs: the per-class safety margin - after ACCUMULATION-GATE; cell = per class (2 cells); population = ACTIVE + VTS; a cell below the floor is published UNDERPOWERED, never fitted"),
   ("#645", "costs: a crypto-era net-EV floor applied to xStocks - after ACCUMULATION-GATE; cell = per class (2 cells); population = ACTIVE; a cell below the floor is published UNDERPOWERED, never fitted"),
   ("rm:25-17", "after B-EXCURSION-RECORD: target geometry for all strategies - after ACCUMULATION-GATE; cell = strategy x class; population = VTS (excursion record); a cell below the floor is published UNDERPOWERED, never fitted"),
   ("rm:25-17b", "geometry: crypto reach ceilings - after ACCUMULATION-GATE; cell = strategy x class, crypto; population = VTS (excursion record); a cell below the floor is published UNDERPOWERED, never fitted"),
   ("rm:25-20", "geometry: per-strategy minimum reward-to-risk - after ACCUMULATION-GATE; cell = strategy x class; population = ACTIVE + REJECTED; a cell below the floor is published UNDERPOWERED, never fitted"),
   ("B-TARGET-MULTIPLE-VS-HORIZON", "geometry: move targets that sit too far - after ACCUMULATION-GATE; cell = strategy x class; population = VTS (excursion record); a cell below the floor is published UNDERPOWERED, never fitted"),
   ("rm:25-26", "geometry: do slower trades clear the fee wall - after ACCUMULATION-GATE; cell = hold-time bucket x class; population = ACTIVE + VTS; a cell below the floor is published UNDERPOWERED, never fitted"),
   ("B-EXIT-MAKER-VS-TAKER-REVIEW", "geometry: maker exits profitable, taker target exits negative - after ACCUMULATION-GATE; cell = exit reason x fee side x class; population = ACTIVE; a cell below the floor is published UNDERPOWERED, never fitted"),
   ("#221", "ranking first (Langston F6): rank the queue, then ask who is missing from it. NO gate clause, reason: a ranking-rule change, code-only, reads no accumulated per-cell data - if its Step 1 finds it fits weights on data, it takes the gate clause then"),
   ("#149", "with #221: per-class RTB refresh cadence calibration - after ACCUMULATION-GATE; cell = per class (2 cells); population = ACTIVE; a cell below the floor is published UNDERPOWERED, never fitted"),
   ("B-FAMILY-POOL-REACHABILITY", "before #648/#201/#529: can each strategy family reach the pool at all - after ACCUMULATION-GATE; an ABSENCE diagnosis: publish UNREACHABLE (zero signals emitted in the signal-evaluation archive), NEVER-SELECTED (signals emitted, zero RTB promotions) or UNDERPOWERED (both non-zero, n below the floor) - never one verdict for all three"),
   ("B-IDEAL-POOL-STARVATION", "before #648/#201/#529: is the ideal pool starved (~4-5% of slots against a nominal 70%) - after ACCUMULATION-GATE; an ABSENCE diagnosis: publish UNREACHABLE (zero signals emitted in the signal-evaluation archive), NEVER-SELECTED (signals emitted, zero RTB promotions) or UNDERPOWERED (both non-zero, n below the floor) - never one verdict for all three"),
   ("#648", "strategies: six never traded - after ACCUMULATION-GATE; an ABSENCE diagnosis: publish UNREACHABLE (zero signals emitted in the signal-evaluation archive), NEVER-SELECTED (signals emitted, zero RTB promotions) or UNDERPOWERED (both non-zero, n below the floor) - never one verdict for all three"),
   ("#201", "strategies: range_trade starved - after ACCUMULATION-GATE; an ABSENCE diagnosis: publish UNREACHABLE (zero signals emitted in the signal-evaluation archive), NEVER-SELECTED (signals emitted, zero RTB promotions) or UNDERPOWERED (both non-zero, n below the floor) - never one verdict for all three"),
   ("#529", "strategies: the strategy-weighting chain - after ACCUMULATION-GATE; cell = strategy x class; population = ACTIVE; a cell below the floor is published UNDERPOWERED, never fitted"),
   ("rm:25-12", "xStock: entry-trigger sweep - after ACCUMULATION-GATE; cell = xStock strategy (19 cells; 2 above 30 on 2026-09-28); population = ACTIVE + VTS; a cell below the floor is published UNDERPOWERED, never fitted"),
   ("rm:25-13", "xStock: geometry reconstruction - after ACCUMULATION-GATE; cell = xStock strategy; population = VTS (excursion record); a cell below the floor is published UNDERPOWERED, never fitted"),
   ("rm:25-14", "xStock: per-strategy entry re-fit - after ACCUMULATION-GATE; cell = xStock strategy; population = ACTIVE + VTS; a cell below the floor is published UNDERPOWERED, never fitted"),
   ("rm:25-2", "regimes: confidence-chain calibration - after ACCUMULATION-GATE; cell = regime x class (5 x 2); population = ACTIVE + VTS; a cell below the floor is published UNDERPOWERED, never fitted"),
   ("rm:25-10", "regimes: crypto confidence modifiers - after ACCUMULATION-GATE; cell = regime, crypto; population = ACTIVE + VTS; a cell below the floor is published UNDERPOWERED, never fitted"),
   ("rm:25-7", "regimes: xStock macro modifiers - after ACCUMULATION-GATE; cell = regime, xStock; population = ACTIVE + VTS; a cell below the floor is published UNDERPOWERED, never fitted"),
   ("rm:16.7", "scores: retire the retired scores. NO gate clause, reason: a code-only removal, reads no accumulated data"),
   ("#588", "scores: a validated quality term in the ranking - after ACCUMULATION-GATE; cell = strategy x class; population = ACTIVE; a cell below the floor is published UNDERPOWERED, never fitted"),
   ("rm:25-4", "scores: SQE recalibration - after ACCUMULATION-GATE; cell = strategy x class; population = ACTIVE + REJECTED; a cell below the floor is published UNDERPOWERED, never fitted"),
   ("rm:25-3", "gates: the sustainability gate - after ACCUMULATION-GATE; cell = one regime x class; population = ACTIVE + VTS; a cell below the floor is published UNDERPOWERED, never fitted"),
   ("rm:25-15", "gates: does the Net Expectancy gate reject winners - after ACCUMULATION-GATE; cell = gate verdict x class; population = REJECTED (name the instrument first; its title still says DATA-BLOCKED); a cell below the floor is published UNDERPOWERED, never fitted"),
   ("rm:25-19", "gates: the Net Expectancy gate's measured judgement - after ACCUMULATION-GATE; cell = gate verdict x class; population = REJECTED + ACTIVE (name the instrument first); a cell below the floor is published UNDERPOWERED, never fitted"),
   ("#644", "gates: the exploration-subsidy decision. NO gate clause, reason: a decision, not a per-cell fit - and it is one of the answers for a permanently underpowered cell, so ACCUMULATION-GATE's Step 1 re-argues its position"),
 ]),
 ("A5", "TRACK A · The evidence — runs continuously; judged at the end", [
   ("rm:25-16", "during A5 (Langston F8): the trade-size / concurrency study reads the sizing-correct paper run; only DAY-ONE-NUMBERS (the decision) waits in B4"),
   ("rm:19-11", "the paper run judged against Kyle's standard"),
 ]),
 ("B1", "TRACK B · Safety now — can start immediately, in parallel with Track A", [
   ("rm:21.1.a", "B1 (Langston F10): the legacy live exit route is a re-entry risk today, whatever the environment"),
   ("B-SEC-HARDEN", "route authorisation (the password rotation moved to B-CREDENTIALS-PRIVATE-REPO, run before the sprint)"),
   ("B-SSH-KEY-CENSUS", "whose are the two unknown keys"),
   ("#615", "the reviewer identity must not read the secrets file"),
   ("COLTRANE-PARITY", "before the Coltrane trial: a privacy check like Langston's"),
   ("#681", "a deploy must not outrun CI"),
   ("#168", "with #681: CI catches a build that crashes on boot"),
   ("P19-B12", "the deploy tool's own executable comes from the reviewed code"),
 ]),
 ("B2", "TRACK B · Risk controls and restart safety — fixed in paper, carried to live", [
   ("B-VENUE-QUIET-ALERTING", "operator alert: a venue has gone quiet (Kyle 2026-09-28: operator alerting joins the sprint)"),
   ("#692", "operator alert: no new trade has opened for a set time because the allowance is full, with manual close / prompt-exit options"),
   ("#634", "the kill switch must not fail open"),
   ("#632", "the daily-loss count survives a restart"),
   ("B-KILLSWITCH-DENOMINATOR", "the kill switch's remaining legs"),
   ("B-TOTAL-DRAWDOWN-WARNING", "a mark-to-market drawdown warning"),
   ("#519", "the daily-loss trip fails loud"),
   ("B-TEC-PRIME-BOOT-RACE", "restarts: the exit loop throws for a tick on open positions"),
   ("B-ENGINE-STOP-DURATION-COLUMN", "an engine stop reports failure when it worked"),
   ("#619", "a restore from backup lacks seeded config"),
   ("B-DASHBOARD-AUTH-RACE", "the portfolio card never recovers from a 401"),
   ("#296", "one rate-limited path for placing and cancelling orders"),
 ]),
 ("B3", "TRACK B · The live engine — environment decided 2026-09-28: live as its own program on the same server", [
   ("#517", "FIRST in B3 (OLD Claude condition 1): the live trade tables - open positions carry NO mode marker today (storage.ts:4519), so this lands BEFORE the program split"),
   ("STAGING-RESIZE", "before the split (Infra condition): one server size up, a second program needs the memory"),
   ("B-LIVE-PROCESS-SPLIT", "after #517 and B-SCHEDULER-FIRST-TICK: live as its own program on the same server - startup made mode-aware (index.ts starts every job unconditionally), Kraken's request budget shared across both programs on one address, archivers and scans run in exactly one program; shapes how rm:21.1 builds live"),
   ("rm:21-3c", "the engine-start health gate refuses live"),
   ("rm:21-3d", "reset functions must not delete both modes' data"),
   ("rm:19-10", "throwing asset-class lookups on the live path"),
   ("rm:21.1", "build live on the paper engine (Option A)"),
   ("#322", "test-in-paper / bypass-in-live switches"),
   ("P19-B6.10", "one source of guardrail values"),
   ("rm:21-3a", "after P19-B6.10: the Live Guardrails tab"),
   ("rm:21.3", "the live guardrails umbrella"),
   ("rm:19-9", "entry-side failure modes (halts, splits, earnings)"),
   ("25-11a", "refuse a position larger than the visible book"),
   ("PROCESS-DEATH-FORM", "decide how live positions are protected if the server dies"),
   ("B-VENUE-RESTING-EXITS", "after PROCESS-DEATH-FORM: build that protection"),
   ("B-KRAKEN-FEE-WATCH", "notice when the exchange changes fees"),
 ]),
 ("B4", "TRACK B · Go-live preparation — last", [
   ("KRAKEN-LIVE-KEY", "the live key: trade-only, no withdrawals, locked to the server"),
   ("LIVE-FEE-SCHEDULE", "after KRAKEN-LIVE-KEY: confirm live fees"),
   ("DAY-ONE-NUMBERS", "after rm:25-16 (run during A5): Kyle sets the live money settings"),
   ("rm:21-3b", "the feed-reliability threshold (Analyst + Langston)"),
   ("rm:21.2", "paper-to-live testing at small size"),
   ("rm:19-17b", "LAST: the go-live switch"),
 ]),
]

if __name__ == "__main__":
    push = json.load(open(os.path.join(HERE, "push_keys.json")))
    seen = [k for _, _, items in WAVES for k, _ in items]
    dup = {k for k in seen if seen.count(k) > 1}
    missing = set(push) - set(seen)
    extra = set(seen) - set(push)
    assert not dup, f"listed twice: {dup}"
    assert not missing, f"sprint items not ordered: {sorted(missing)}"
    assert not extra, f"ordered but not in the sprint: {sorted(extra)}"
    # S2 (Langston): every note that opens with "after <KEY>" must name an item that exists and comes EARLIER
    idx = {k: i for i, k in enumerate(seen)}
    import re as _re
    bad = []
    for _, _, items in WAVES:
        for k, note in items:
            for dep in _re.findall(r"\bafter ([#A-Za-z0-9:._-]*[#:A-Z0-9][#A-Za-z0-9:._-]*)", note):
                dep = dep.rstrip(".:,")
                if dep not in idx: bad.append((k, dep, "missing")); continue
                if idx[dep] >= idx[k]: bad.append((k, dep, "not earlier"))
    assert not bad, f"after-X references broken: {bad}"
    print("ordered", len(seen), "of", len(push))
