"""The working ORDER of the push to live (CC-B draft, 2026-09-28, for Langston's review then Kyle).
Two tracks run side by side and meet at go-live:
  Track A — the trading system: foundations -> mechanics (+ learning data alongside) -> tuning -> the evidence.
  Track B — live-mode readiness: the environment decision, safety now, risk controls, restart/ops, the live engine, go-live prep.
Wave 0 is this week's urgent and cheap items. Within a wave, the listed order is the working order; an item marked
'after X' must wait for X. Every push item must appear exactly once (asserted)."""
import io, json, os
HERE = os.path.dirname(os.path.abspath(__file__))

WAVES = [
 ("0", "NOW — urgent, cheap, or already in flight (this week)", [
   ("B-XSTOCK-BID-TRIGGER-RELAND", "midpoint off (Kyle 2026-09-28: finished and deployed BEFORE the push starts): paper xStock stop/target triggers back on the bid"),
   ("B-VTS-MARK-SIDE", "midpoint off, before the push: the VTS xStock prices on the right side (8a-P4c increments 2-3)"),
   ("B-VTS-NO-DECISION-VALVE", "midpoint off, before the push: a VTS trade with no usable sell price no longer books its timeout at the midpoint"),
   ("RULINGS-DURABILITY", "cheap and irreversible if lost: copy Langston's rulings file to a read-only replica"),
   ("DISK-HEADROOM", "database at 81% (critical): confirm the October 1 move of August to warm storage lands; then (Kyle 2026-09-28) move one month of one-minute price bars as the proof and flip their hot window 365 -> 30 days (~19 GB out); then measure months of headroom"),
   ("PAPER-STANDARD", "set the numbers for 'comfortable in paper' BEFORE the evidence comes in"),
   ("PLAN-ID-COLLISIONS", "part of rewriting the plan: no two items share a number"),
   ("B-OHLC-FRAME-GUARD", "in flight: only the on-screen check is left"),
   ("B-REST-SIDES-TO-CACHE", "built and reviewed: deploy after the 2026-09-30 VTS window closes"),
   ("B-BOOK-STATE-RESTART-DURABLE", "built and reviewed: deploy with the one above"),
   ("F-G-1-REOPEN", "the OHLC writer can put an older bar over a newer one — it feeds the bars signals are built from"),
   ("B-PRICE-SIDE-BY-JOB", "in flight: its xStock increments follow the 09-30 window"),
 ]),
 ("A1", "TRACK A · Foundations — the things that corrupt everything downstream", [
   ("B-UNIVERSE-REFRESH-ACTS", "first link of the identity chain"),
   ("B-SYMBOL-CLASS-IDENTITY", "after B-UNIVERSE-REFRESH-ACTS: a ticker shared by a coin and a stock becomes two instruments"),
   ("B-RTB-SIGNAL-IDENTITY", "after B-SYMBOL-CLASS-IDENTITY"),
   ("B-VTS-CLASS-LABEL-INTEGRITY", "after B-SYMBOL-CLASS-IDENTITY: correct the mislabelled VTS rows"),
   ("B-CLOSED-TRADES-CLASS-BACKFILL", "after B-SYMBOL-CLASS-IDENTITY"),
   ("NONFIAT-FORK", "Kyle's decision: exclude plain currency pairs and non-dollar crypto now"),
   ("B-NONFIAT-QUOTE-DENOMINATION", "the exclusion itself, if small"),
   ("B-QUOTE-ADMISSION-LEGACY-SWEEP", "with the exclusion: what the old allowed-pairs list is for"),
   ("B-QUOTE-LEG-INTEGRITY", "with the exclusion"),
   ("B-PRICE-FLOOR-REVIEW", "replace the $0.25 floor with a real market-depth test"),
   ("B-VENUE-PAIRS-REINIT", "a changed exchange price step must not refuse orders"),
   ("B-SCAN-BREADTH-DECLINE", "why the scanner sees so few pairs — breadth feeds selection"),
   ("B-XSTOCK-LIVE-FEED", "the xStock feed became our trading feed without a decision — decide and fix"),
   ("row:6", "a bound on how old a price may be when used"),
   ("B-PRICE-STALENESS-BOUND", "the last-known-good price is re-served with no age bound"),
   ("B-EQUITY-RECONNECT-STALL-TIMER", "a stalled xStock reconnect leaves positions unwatched"),
   ("B-WS-SUBSCRIBE-CLASS-FILTER", "the crypto subscribe set is not class-filtered"),
   ("#506", "book subscriptions never unsubscribe"),
   ("B-BOOK-SUBSCRIPTION-REACH", "after #506: subscribe the order book for the whole pool, not ~3 coins"),
   ("B-CRYPTO-MARK-AGE-GATE", "crypto mark age"),
   ("B-XSTOCK-SESSION-FRESHNESS", "xStock entry-age limit vs the exit standard Kyle ruled"),
   ("B-XSTOCK-ENTRY-COMPARATOR", "xStock entry-price cross-check"),
   ("B-DECIDED-INTENT-INDEX", "xStock's three definitions of 'the price' from one frame"),
   ("B-POST-GRID-MUTATION-CENSUS", "what changes a stop after it is rounded"),
   ("row:7", "the VTS reads prices through the shared accessor"),
   ("#1033", "an absent volume is stored as zero and the liquidity filter reads it"),
   ("#972", "xStock ATR reads empty around the open and close"),
   ("#566", "volatility measured with a lag"),
   ("CODEX-PRICING-REVIEW", "after the price items: an independent review of the whole price layer"),
   ("B-SIZING-DEC-RESTORE", "paper sizing to Kyle's intent (~$140-150 a trade, 15-20 open)"),
   ("#628", "with B-SIZING-DEC-RESTORE: its two sizing sites"),
 ]),
 ("A2", "TRACK A · Mechanics, stage by stage — can start as A1's pieces land", [
   ("#233", "signals: drift and volume inputs fed as fixed defaults"),
   ("#199", "strategies: xStock volume confirmation removed for lack of an honest feed"),
   ("row:3m-ENUM", "strategies: volatility_edge's pattern path is silently dead"),
   ("B-SILENT-STRATEGY-CENSUS", "strategies: three wired strategies never evaluated"),
   ("B-TARGET-FABRICATION", "signals: default targets the strategy never chose"),
   ("#574", "SQE: a made-up volatility input in the ranker"),
   ("B-RTB-REFRESH-CONSOLIDATE", "RTB: the net-EV backstop removed on thin evidence"),
   ("#570", "RTB: one refresh bucket fires but does not refresh"),
   ("#699", "RTB: does promotion evict, or is the screen stale"),
   ("rm:19.2", "SQE: verify every score calculates correctly"),
   ("B-ENTRY-LEVEL-RECHECK", "open: re-check a signal's levels against the current price before the fill"),
   ("B-INTENT-ENTRY-PARITY", "open: two entry routes bypass the price grid"),
   ("B-GRID-LIVE-PATH-PARITY", "open: grid rounding on the live order path"),
   ("RESTING-ORDER-DEADLINE", "open: a resting order's deadline runs even when no price is usable"),
   ("#630", "open: exercise the maker-order deadline once"),
   ("B-EXIT-TRIGGER-FILL-PARITY", "close: exits fire on the price they would fill at"),
   ("B-EXIT-TICKER-LEG-ADAPTER-SIDES", "close: the exit path sees both price sides"),
   ("B-BOOK-STATE-RING-INDEPENDENT-BOUND", "close: xStock exit plausibility bound"),
   ("#204", "close: xStock stop prices at the wrong scale"),
   ("row:3h.b", "close: remove the second exit implementation"),
   ("B-EXIT-LATCH-INVESTIGATION", "close: is the hold-past-target a label or a real exit defect"),
   ("EXIT-PATH-AUDIT-MAP", "close: map the exit audit's items to homes"),
   ("#166", "close: the TEC stale-cache fence keeps firing"),
   ("B-CLOSE-WRITER-COSTS", "close: no close without a trade record, no invented zero fees"),
   ("B-SCHEDULER-FIRST-TICK", "restarts: every scheduled job runs twice after a restart"),
   ("#585", "restarts: auto-resume skips a malformed session"),
   ("B-STRING-TRUTHINESS-GUARDS", "hygiene: guards that treat '0' as true"),
   ("B-GUARD-COVERAGE-AUDIT", "hygiene: which guards cover which paths"),
   ("B-LEARNING-SYSTEM-CENSUS", "hygiene: old learning systems still wired"),
   ("DEAD-CODE-REACHABILITY", "hygiene: which dead code a trade can still reach (pulls items forward if any)"),
   ("B-TRADING-ENGINE-REMOVAL", "legacy removal, after the census confirms it dead: the older second trading engine (Kyle 2026-09-28)"),
   ("B-SQE-DEADCODE-PURGE", "legacy removal, after the census: a dead SQE copy that checks fewer gates"),
   ("rm:16.6", "legacy removal, after the census: the old trailing-percent exit code, so it cannot re-enter a live exit"),
   ("#589", "legacy removal, after the census: the unused calibrated-profit calculator"),
   ("B-WS-V1-RESIDUE-SWEEP", "legacy removal, after the census: the dead first-generation Kraken price handler"),
   ("B-MODE-PREDICATE-SWEEP", "hygiene: readers that would mix live and paper P&L"),
   ("row:8", "paper truth: fill-integrity detector"),
   ("B-COST-MATH-CONSOLIDATION", "paper truth: one home for cost maths"),
   ("#527", "paper truth: xStock friction components"),
   ("B-IMPLEMENTATION-SHORTFALL", "paper truth: separate stale-signal cost from execution cost"),
   ("B-GRID-REFUSAL-RATE", "paper truth: how often the grid refuses"),
   ("B-VALIDATE-OBSERVABILITY", "paper truth: make validation failures visible"),
   ("B-DIAG-READ-INTEGRITY", "paper truth: diagnostics that read a status code as data"),
   ("B-FILTER-DIAG-XSTOCK", "paper truth: the empty xStock decline table"),
   ("#664", "paper truth: a hardcoded 'strategies evaluated'"),
   ("#419", "paper truth: funnel counts under errors"),
   ("#549", "paper truth: Open Trades field gaps"),
   ("#561", "paper truth: volume / order book columns in Open Trades"),
   ("#547", "paper truth: the Analyst's July findings (owner reads)"),
   ("#522", "LAST in A2: the full runtime pipeline audit, both classes, end to end"),
   ("#235", "with #522: the crypto pipeline validated end to end"),
 ]),
 ("A3", "TRACK A · Learning data — alongside A2; must finish before tuning reads the data", [
   ("B-OUTCOME-CORPUS-CAPTURE", "what each VTS trade earned, recorded durably, with a measured/defaulted flag on its inputs. NOT a deletion clock: the 90-day delete was fixed 2026-07-30/08-06 (365 days, archive before delete); nothing is due for deletion before 2027-05"),
   ("B-PAPER-LANE-PROVENANCE", "paper records its decision inputs"),
   ("T-W20C-SCALAR-LEG", "after B-PAPER-LANE-PROVENANCE: the parity harness proves recorded history replays"),
   ("#515", "remaining learning columns on the active path"),
   ("#631", "entry-mode fields on the active archive"),
   ("#504", "regime on maker/taker shadow rows"),
   ("B-DECISION-INSTANT-QUOTE", "the exact quote at decision time"),
   ("B-EXIT-DECISION-RUNG-STAMP", "which price rung an exit used"),
   ("B-TRADE-RECORD-JOINABILITY", "trade records join across stores"),
   ("B-VPNL-WRITER-BOUND", "an unbounded learning column"),
   ("#658", "VTS posture multipliers contaminating learning rows"),
   ("#220", "an error thrown 64,494 times in VTS strategy runs"),
   ("#1072", "the price-history recorder's frozen symbol set"),
   ("B-ARCHIVE-WRITER-LIFECYCLE", "the archive writer's lifecycle"),
   ("B-EPOCH-PARITY-FENCE", "one home for the calibration epoch"),
   ("B-ROLLBACK-EPOCH-FORWARD", "epochs across a rollback"),
   ("#590", "calibration store reset at the formula change"),
   ("B-OBS-WINDOW-EVIDENCE-CAPTURE", "capture window evidence at the event"),
   ("B-PROVENANCE-LOSS-CENSUS", "where decision provenance is lost"),
   ("#231", "ablation record id gap"),
   ("rm:25-9", "xStock per-pair correlation data"),
   ("row:9", "LAST in A3: the gate for restarting the learning record clean after the fixes"),
 ]),
 ("A4", "TRACK A · Tuning — reads the clean data; costs -> geometry -> strategies -> regimes -> scores -> gates -> ranking", [
   ("#914", "costs: the per-leg cost term"),
   ("rm:25-18", "costs: the per-class safety margin"),
   ("#645", "costs: a crypto-era net-EV floor applied to xStocks"),
   ("B-EXCURSION-RECORD", "geometry: record how far trades travel"),
   ("rm:25-17", "after B-EXCURSION-RECORD: target geometry for all strategies"),
   ("rm:25-17b", "geometry: crypto reach ceilings"),
   ("rm:25-20", "geometry: per-strategy minimum reward-to-risk"),
   ("B-TARGET-MULTIPLE-VS-HORIZON", "geometry: move targets that sit too far"),
   ("rm:25-26", "geometry: do slower trades clear the fee wall"),
   ("B-EXIT-MAKER-VS-TAKER-REVIEW", "geometry: maker exits profitable, taker target exits negative"),
   ("#648", "strategies: six never traded"),
   ("#201", "strategies: range_trade starved"),
   ("#529", "strategies: the strategy-weighting chain"),
   ("B-FAMILY-POOL-REACHABILITY", "strategies: reachability in the family pool"),
   ("B-IDEAL-POOL-STARVATION", "strategies: the ideal pool gets 4-5% of slots"),
   ("rm:25-12", "xStock: entry-trigger sweep"),
   ("rm:25-13", "xStock: geometry reconstruction"),
   ("rm:25-14", "xStock: per-strategy entry re-fit"),
   ("rm:25-2", "regimes: confidence-chain calibration"),
   ("rm:25-10", "regimes: crypto confidence modifiers"),
   ("rm:25-7", "regimes: xStock macro modifiers"),
   ("rm:16.7", "scores: retire the retired scores"),
   ("#588", "scores: a validated quality term in the ranking"),
   ("rm:25-4", "scores: SQE recalibration"),
   ("rm:25-3", "gates: the sustainability gate"),
   ("rm:25-15", "gates: does the Net Expectancy gate reject winners"),
   ("rm:25-19", "gates: the Net Expectancy gate's measured judgement"),
   ("#644", "gates: the exploration subsidy decision"),
   ("#221", "ranking: crypto vs xStock signals in one queue"),
   ("#149", "ranking: per-class RTB refresh cadence"),
 ]),
 ("A5", "TRACK A · The evidence — runs continuously; judged at the end", [
   ("rm:19-11", "the paper run judged against Kyle's standard"),
 ]),
 ("B1", "TRACK B · Safety now — can start immediately, in parallel with Track A", [
   ("B-SEC-HARDEN", "rotate the public owner password first (Kyle), then route authorisation"),
   ("B-SSH-KEY-CENSUS", "whose are the two unknown keys"),
   ("#615", "the reviewer identity must not read the secrets file"),
   ("COLTRANE-PARITY", "before the Coltrane trial: a privacy check like Langston's"),
   ("#681", "a deploy must not outrun CI"),
   ("#168", "with #681: CI catches a build that crashes on boot"),
   ("P19-B12", "the deploy tool's own executable comes from the reviewed code"),
 ]),
 ("B2", "TRACK B · Risk controls and restart safety — fixed in paper, carried to live", [
   ("B-VENUE-QUIET-ALERTING", "operator alert: a venue has gone quiet (Kyle 2026-09-28: operator alerting joins the push)"),
   ("#692", "operator alert: no new trade has opened for a set time because the allowance is full, with manual close / prompt-exit options"),
   ("#634", "the kill switch must not fail open"),
   ("#632", "the daily-loss count survives a restart"),
   ("B-KILLSWITCH-DENOMINATOR", "the kill switch's remaining legs"),
   ("B-TOTAL-DRAWDOWN-WARNING", "a mark-to-market drawdown warning"),
   ("#519", "the daily-loss trip fails loud"),
   ("B-TEC-PRIME-BOOT-RACE", "restarts: the exit loop throws for a tick on open positions"),
   ("#521", "restarts: nothing notices a dead engine"),
   ("B-ENGINE-STOP-DURATION-COLUMN", "an engine stop reports failure when it worked"),
   ("#619", "a restore from backup lacks seeded config"),
   ("B-DASHBOARD-AUTH-RACE", "the portfolio card never recovers from a 401"),
   ("#296", "one rate-limited path for placing and cancelling orders"),
 ]),
 ("B3", "TRACK B · The live engine — after Kyle's production-environment decision", [
   ("rm:21.1.a", "hard blocker: the legacy live exit route"),
   ("rm:21-3c", "the engine-start health gate refuses live"),
   ("rm:21-3d", "reset functions must not delete both modes' data"),
   ("rm:19-10", "throwing asset-class lookups on the live path"),
   ("rm:21.1", "build live on the paper engine (Option A)"),
   ("#322", "test-in-paper / bypass-in-live switches"),
   ("P19-B6.10", "one source of guardrail values"),
   ("rm:21-3a", "after P19-B6.10: the Live Guardrails tab"),
   ("#517", "after rm:21.1: the live trade tables"),
   ("rm:21.3", "the live guardrails umbrella"),
   ("rm:19-9", "entry-side failure modes (halts, splits, earnings)"),
   ("25-11a", "refuse a position larger than the visible book"),
   ("PROCESS-DEATH-FORM", "decide how live positions are protected if the server dies"),
   ("B-VENUE-RESTING-EXITS", "after PROCESS-DEATH-FORM: build that protection"),
   ("B-KRAKEN-FEE-WATCH", "notice when the exchange changes fees"),
 ]),
 ("B4", "TRACK B · Go-live preparation — last", [
   ("KRAKEN-LIVE-KEY", "the live key: trade-only, no withdrawals, locked to the server"),
   ("LIVE-FEE-SCHEDULE", "after KRAKEN-LIVE-KEY: confirm live fees"),
   ("rm:25-16", "the trade-size / concurrency study at the real balance"),
   ("DAY-ONE-NUMBERS", "after rm:25-16: Kyle sets the live money settings"),
   ("rm:21-3b", "the feed-reliability threshold (Analyst + Langston)"),
   ("rm:21.2", "paper-to-live testing at small size"),
   ("rm:19-17b", "LAST: the go-live switch"),
 ]),
]

if __name__ == "__main__":
    push = json.load(open(os.path.join(HERE, "push_keys.json")))
    seen = [k for _, _, items in WAVES for k, _ in items]
    dup = {k for k in seen if seen.count(k) > 1}
    missing = set(push) - set(seen)
    extra = set(seen) - set(push)
    assert not dup, f"listed twice: {dup}"
    assert not missing, f"push items not ordered: {sorted(missing)}"
    assert not extra, f"ordered but not in the push: {sorted(extra)}"
    print("ordered", len(seen), "of", len(push))
